config/routes.rb
DEPOT::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do 
    get 'login' => :new 
    post 'login' => :create 
    delete 'logout' => :destroy 
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do 
  get :who_bought, :on => :member 
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DEPOT</title>
  <%= stylesheet_link_tag "scaffold"%>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>       <!--prevents cross-site request forgery attacks-->
</head>
<body id="store">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "PRAGMATIC STORE" %> <!--sets page heading-->
	</div>
	<div id="columns">
		<div id="side">
			<a href="http://localhost:3000">HOME</a><br />
			<a href="http://www..../faq">QUESTIONS</a><br />
			<a href="http://www..../news">NEWS</a><br />
			<a href="http://www..../contact">CONTACT</a><br />
			<a><%= Time.now %></a><br />
			
			<% if session[:user_id] %> 
				<br /> 
					<%= link_to 'Orders', orders_path %><br /> 
					<%= link_to 'Products', products_path %><br /> 
					<%= link_to 'Users', users_path %><br /> 
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %> 
			<% end %>
			<div id="cart">
				<% if @cart %>
					<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %><!--function in helper module, hiding cart if itz empty.-->
						<%= render @cart %>
					<% end %> 
				<% end %>
			</div>
		</div>
		<div id="main">
			<%= yield %>      <!--this is where actual page is generated.-->
		</div>
	</div>
</body>
</html>